### ISSUE TITLE
Breeding between dragons is broken

### ISSUE THREAD

**Issue by FantasyRedFox** [Alex-the-666/Ice_and_Fire#1098]
There seems to be a bug in the breeding of dragons. When I attempted to breed two stage 5 fire dragons, there was no egg produced. I haven't seen if this bug concerns ice dragons as well, but I would appreciate it if you looked into this. Thank you!

**Comment by AlexModGuy** [comment]
fixed

**Comment by GundunUkan** [comment]
Breeding isn't bugged, the two dragons just need to be on even ground. Sometimes an egg still isn't produced, but that may be intended.
