### ISSUE TITLE
Terraforged mausoleum crash

### ISSUE THREAD

**Issue by Hukenon** [Alex-the-666/Ice_and_Fire#3402]
Often when a mausoleum is generated, the game will crash, only reloading at last game save or being unable to load. Problem persists on client or server, and doesn't always happen. But it is definitely the mausoleum that's doing it. Other structures have all generated just fine (as far as I can tell), and on personal testing on singleplayer I have been able to generate several. Main issue is server crashes upon being generated. 

I tried disabling the mausoleum in spawn chance (set it to 0) and changing biomes it can spawn in to none crashes the game. I hope I'm not misdiagnosing the issue- or went to the wrong place :)

[1.16.4] on version 2.1.4 (I will try testing with newest versions of both mods)

**Comment by azachariou** [comment]
I've been running into the same issue. Here's a crash log if it helps. https://pastebin.pl/view/55b32194

**Comment by BugmanBugman** [comment]
Update to the latest. #3359 should fix this

**Comment by Won-Ton** [comment]
> Update to the latest. #3359 should fix this

It doesn't.
Explanation of the issue here: https://github.com/Alex-the-666/Ice_and_Fire/issues/3390#issuecomment-755222331
And the problematic code still exists [here](https://github.com/Alex-the-666/Ice_and_Fire/blob/1.16.3/src/main/java/com/github/alexthe666/iceandfire/world/structure/MausoleumPiece.java#L47-L49).

**Comment by TheBv** [comment]
It does actually fix it. But like I, when I made my first request, mentioned what I created was mostly a **hotfix**. 
You're probably right with what you said but by only expanding the bounding box once, the thing you mentioned doesn't seem to happen anymore.
I still agree with you that we should probably not expand and parse the mutable bounding box into the super function but for now I haven't experienced any issues with the mausoleum even when generating thousands of chunks with mausoleums generating everywhere.
Edit: The reason why I had the idea to only expand it once was because the ~~gorgon temple~~ graveyard does the same thing so that should probably get changed as well.
