### ISSUE TITLE
Dread Spawner Ticking Entity Crash [2.1.7]

### ISSUE THREAD

**Issue by Blunder-G** [Alex-the-666/Ice_and_Fire#3960]
When I look around in the game and saying "Wow... TerraForged is awesome, man."  I came across one of those black stone structures that only appear in glacial biomes and after 3 minutes game crashed.

Here is the report: 
[crash-2021-06-14_22.55.28-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/6650956/crash-2021-06-14_22.55.28-server.txt)

**Comment by TheBv** [comment]
Seems to have something to do with a mod called "Adaptive Performance Tweaks".
I don't want to blame that mod entirely for the issue but you might want to create an issue on his [github ](https://github.com/MarkusBordihn/adaptive_performance_tweaks) and we might be able to work something out together.
The dread spawners are a bit weird and I haven't done anything with them so if possible I'd rather not touch that code in fear or breaking things ^^"

**Comment by Blunder-G** [comment]
> Seems to have something to do with a mod called "Adaptive Performance Tweaks".
> I don't want to blame that mod entirely for the issue but you might want to create an issue on his [github ](https://github.com/MarkusBordihn/adaptive_performance_tweaks) and we might be able to work something out together.
> The dread spawners are a bit weird and I haven't done anything with them so if possible I'd rather not touch that code in fear or breaking things ^^"

I will send this crash to the APTweaks. It seems APTweaks is incopmat with some spawning methods.

**Comment by MarkusBordihn** [comment]
I took a look into this issue and it's seems TileEntityDreadSpawner is not extending the MobSpawnerTileEntity, which I would expect, instead it is creating it own instance which cause this issue.

I fixed the issue on my side by a stricter type check, but recommend to change the class TileEntityDreadSpawner to be an instance of net.minecraft.tileentity.MobSpawnerTileEntity, if possible in the long term.

Keep the good work with this mod, it's one of my favorites mods. 😉

**Comment by TheBv** [comment]
Simply extending by MobSpawnerTileEntity sadly doesn't resolve the issue since if you do so the tile entity becomes invalid.
This is due to the fact that you can't redefine the TileEntityType the mob spawner then has. 
So when loading in the block/entity it tests if the block "minecraft:spawner" is present at the TileEntities position. Which isn't the case since the block at it's place is "iceandfire:dread_spawner". 
As far as I'm aware you can't change the TileEntityType without a ~~mixin~~ accesstransformer since it's private and the class MobSpawnerTileEntity doesn't have a constructor that accepts a TileEntityType as a parameter.

One could also change to normal minecraft spawners but then you can't define your own texture for it which is why I assume Alex' has gone through all this trouble...

I'm pretty sure all of this is the reason why twilight forest for instance has done exactly the [same ](https://github.com/TeamTwilight/twilightforest/blob/1.16.x/src/main/java/twilightforest/tileentity/spawner/TileEntityTFBossSpawner.java) 
If I'm overlooking anything please let me know but I don't think you can create a custom spawner(block) while extending the class MobSpawnerTileEntity

**Comment by Blunder-G** [comment]
Problem solved. At least APTweaks's creator said that solved with new update.
