### ISSUE TITLE
Unable to interact with Snow Villagers in multiplayer - with Sponge

### ISSUE THREAD

**Issue by Rutes** [Alex-the-666/Ice_and_Fire#398]
Maybe it's just me? Works fine in a single-player world, but I've removed every other mod from my server and still get nothing when I right-click the Snowy folks. No crashes, the server throws some errors, but keeps chugging along. On the client side it's like they're just Nitwits.

server log:

> 
> [17:45:17] [Server thread/INFO]: Rutes joined the game
> [17:45:35] [Server thread/INFO]: [Rutes: Set own game mode to Creative Mode]
> [17:45:52] [Server thread/INFO]: [Rutes: Set own game mode to Survival Mode]
> [17:45:55] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.1.0-BETA-2815]
> 	at net.minecraft.server.MinecraftServer.redirect$onRun$zja000(MinecraftServer.java:4007) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1854) ~[ady.class:?]
> 	at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:262) ~[ady.class:?]
> 	at com.github.alexthe666.iceandfire.entity.EntitySnowVillager.func_184645_a(EntitySnowVillager.java:44) ~[EntitySnowVillager.class:?]
> 	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2549) ~[pa.class:?]
> 	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
> 	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
> 	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) ~[PacketUtil.class:1.12.2-2555-7.1.0-BETA-2815]
> 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkl000(SourceFile:539) ~[hv$1.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 7 more
> [17:45:58] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.1.0-BETA-2815]
> 	at net.minecraft.server.MinecraftServer.redirect$onRun$zja000(MinecraftServer.java:4007) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1854) ~[ady.class:?]
> 	at net.minecraft.entity.passive.EntityVillager.func_184645_a(EntityVillager.java:262) ~[ady.class:?]
> 	at com.github.alexthe666.iceandfire.entity.EntitySnowVillager.func_184645_a(EntitySnowVillager.java:44) ~[EntitySnowVillager.class:?]
> 	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2549) ~[pa.class:?]
> 	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
> 	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
> 	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) ~[PacketUtil.class:1.12.2-2555-7.1.0-BETA-2815]
> 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkl000(SourceFile:539) ~[hv$1.class:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 7 more
> [17:46:02] [Server thread/INFO]: Rutes lost connection: Disconnected

**Comment by Rutes** [comment]
scratch that... all mods disabled EXCEPT sponge... 
could be related to these issues?
https://github.com/Alex-the-666/Ice_and_Fire/issues/297
https://github.com/SpongePowered/SpongeForge/issues/1748

**Comment by AlexModGuy** [comment]
yeah probably. sponge is really finnicky when i to comes to modded mobs

**Comment by Sunconure11** [comment]
I can confirm it still persists.

**Comment by gabizou** [comment]
Fixed on sponge's end. SpongeForge 3182 has the fix.

**Comment by AlexModGuy** [comment]
ok then good good

**Comment by Rutes** [comment]
actually the snow villagers are still not working... No longer throwing errors to console, though. There is also a new version of Ice & Fire out today. So, I will test with everything at latest and re-open a new if still a problem.
