### ISSUE TITLE
Crash when approaching Mausoleum, appears to be dreadknight related - [iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-01-31]

### ISSUE THREAD

**Issue by Teknosqurl** [Alex-the-666/Ice_and_Fire#4744]
We are experiencing crashes when approaching what I believe is a mausoleum. The crash refers to an entity error with a Dreadknight. This originally happened on a server, and we were able to replicate in Singleplayer as well however. I don't believe this is a mod conflict either, but I am of course including the mod list just in case. If any more info is needed, please let me know.

I couldn't find an open issue about this, but if I missed it and this is a duplicate, my apologies.

Server and Single Player are running Forge 1.18.2-40.2.0. Ice and Fire version is iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-01-31 (also included in issue title.)

<details>
<summary>Mod List</summary>
Adorn-3.5.0+1.18.2-forge
arcaneadditions-1.4.2
arsarsenal-1.1.1-1.18.2
arsomega-2.6.1
ars_elemental-1.18.2-0.4.9.7.3
ars_instrumentum-1.18.2-2.4.2
ars_nouveau-1.18.2-2.6.3
artifacts-1.18.2-4.0.7
awesomedungeon-2.0.11
balm-3.2.2+0
better-end-1.1.1
camera-1.18.2-1.0.2
citadel-1.11.3-1.18.2
CosmeticArmorReworked-1.18.2-v2
curios-forge-1.18.2-5.0.7.1
Decorative+Blocks-forge-1.18.2-2.1.0
DungeonCrawl-1.18.2-2.3.9
Enhanced_Celestials-forge-1.18.2-2.0.7
EpicFight-18.2.3-beta
expandability-6.0.0
FallingTree-1.18.2-3.5.3
FarmersDelight-1.18.2-1.1.2
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
geckolib-1.18-forge-3.0.18
gravestone-1.18.2-1.0.1
hedgemagic-1.2.1
honeyexpansion-1.1.1
iceandfire-2.1.12-1.18.2-SNAPSHOT+build.2023-01-31
infernal-expansion-1.18.2-2.5.0
jei-1.18.2-9.7.0.209
journeymap-1.18.2-5.8.5-forge
kotlinforforge-3.6.0-obf
libraryferret-forge-1.18.2-3.0.0
lootr-1.18.2-0.2.23.60
mna-1.7.2.5
NethersDelight-1.18.2-2.2.0
paradise-lost-1.6.9+1.18.2
Patchouli-1.18.2-71.1
Ping-1.18-1.8.0
reap-1.18.2-1.0.0
relics-1.18.2-0.4.1.8
repurposed_structures_forge-5.1.14+1.18.2
selene-1.18.2-1.17.9
supplementaries-1.18.2-1.4.7
tenshilib-1.18.2-1.6.8-forge
ToolBelt-1.18.2-1.18.8
toomanyglyphs-1.18.1-2.0.7.15321
torohealth-1.18-forge-2
TravelersBackpack-1.18.2-7.1.2
twilightforest-1.18.2-4.1.1102-universal
walljump-forge-1.18.1-1.3.7
waystones-forge-1.18.2-10.1.0
YungsApi-1.18.2-Forge-2.0.8
YungsBetterDungeons-1.18.2-Forge-2.1.0
YungsBetterMineshafts-1.18.2-Forge-2.2
YungsBetterStrongholds-1.18.2-Forge-2.1.1
YungsExtras-1.18.2-Forge-2.1.0
</details>

crash log:
[crash.txt](https://github.com/AlexModGuy/Ice_and_Fire/files/11201839/crash.txt)

**Comment by TheBv** [comment]
Do any of these mods add banner patterns or do anything that could influence banners?

**Comment by moh1655** [comment]
Im having the same issue as well.

**Comment by Teknosqurl** [comment]
> Do any of these mods add banner patterns or do anything that could influence banners?

@TheBv The only mods which relate to banners are Twilight Forest and Repurposed Structures. Repurposed Structures adds additional banners to vanilla entities/structures. Twilight Forest adds banners which are collectable within the Twilight Forest. None remove or change banners.

**Comment by TheBv** [comment]
Could you possibly try out the latest snapshot and see if the issue has been resolved? https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot

**Comment by Teknosqurl** [comment]
Thank you very much, I will get it updated and check on server and Singleplayer to see if it works, will let you know how it goes.

**Comment by AvianAnalyst** [comment]
@TheBv I tried updating to the latest snapshot, and am unable to spawn dread knights. Happy to send any info, but it looks like the same problem as this and issues #4814  and #4779 

Happy to test out any fixes as well/start a new issue/share any information you might want or need

**Comment by Chiseris** [comment]
I just got the exact same crash when opening the mausoleum with the key, our ice and fire mod is updated to the most recent version from 3/12/23. I also can't join the server because it instant crashes the minute I'm loaded in from the mausoleum

**Comment by TheBv** [comment]
I've went ahead and cross referenced the mods used in both of the crash logs provided by the different issues.
I did not manage to reproduce the issue, which leads me to believe that the issue has been resolved/was caused by a different mod.
Here's the list of mods I tried to include (all at once):
```
repurposed structures
feature nbt deadlock be gone
twilight forest
rubidium
prefab
sophistiacted core
architectury
mr crayfish furniture mod
patchouli
curios
botania
farmers delight
refined storage
beyond earth
enchantinginfuser
cyclic
geckolib3
cucumber
clumps
naturescompass
artifacts
goprone
terrablender
jade
flywheel
create
puzzleslib
expandability
createaddition
```
If someone can reproduce this issue with updated mods (ideally a small list) I'd be happy to look into it more but for now I'm not sure how I can effectively reproduce the issue.

**Comment by AvianAnalyst** [comment]
Thank you for the effort, I'll update mods and do some testing and see if a) i'm still having the issue b) if i can track down a specific mod that causes the issue to show up and will update you. I should be able to get to this later today or tomorrow.

**Comment by Chiseris** [comment]
> 

I also tried with the mods listed above that we also have on our modpack and didn't get any crash like the one we get on our server, I can send you my modpack list and see if maybe you can find out which mod could be causing it and maybe it's a mod we all have in common?

This is the crash we get when we try to go near a mausoleum in our server --> https://pastebin.com/iLPfPzjG

**Comment by TheBv** [comment]
Sending me the modpack would help out a lot. Having to download/find them individually is quite tedious ^^

**Comment by Chiseris** [comment]
> Sending me the modpack would help out a lot. Having to download/find them individually is quite tedious ^^

https://drive.google.com/file/d/14rA9xTWlFsxjVxMuDAfUbZflRI9-KHuz/view?usp=sharing This is the google drive to our curseforge modpack with resource packs as well just in case

**Comment by Chiseris** [comment]
> Sending me the modpack would help out a lot. Having to download/find them individually is quite tedious ^^

I found the mod causing our crash, it was caused by BlueSkies! Going near or in the mausoleums no longer crash me without BlueSkies installed.

**Comment by TheBv** [comment]
Thanks for the info I figured out the issue and it does have to do with how BlueSkies registers some things. 
I'll need to look into it further and ideally create a patch for ice and fire as well (if possible) since it's not just that mod that's causing these issues.

**Comment by TheBv** [comment]
@Chiseris https://gitlab.com/modding-legacy/blue-skies/-/issues/160
I guess that won't get fixed... Time for me to implement an unnecessary workaround because of other peoples incompetence...

**Comment by TheBv** [comment]
https://github.com/AlexModGuy/Ice_and_Fire/releases/tag/1.18.2-latest-snapshot
This fixes that issue. Banners are broken and will just be black. Nothing I can do against that.
If people want things to get fixed in the future: look out for mods that have extra signs in them; they most likely are causing the issue.
