### ISSUE TITLE
[Bug]: Commands added by plugins on Magma 1.18.2 (forge/plugins core) do not work with Ice and Fire

### ISSUE THREAD

**Issue by Bayti4EkPressF** [Alex-the-666/Ice_and_Fire#4815]
### What happened?

When I start the server on 1.18.2 using Magma, all commands that were added by plugins stop working. I removed all mods except ice and fire and citadel and still nothing worked.

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
I don't know how this will help, but:
[30Mar2023 00:14:41.841] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.2.1, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[30Mar2023 00:14:41.845] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.5 by Oracle Corporation
[30Mar2023 00:14:41.959] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/opc/servers/VireynMCOBT/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[30Mar2023 00:14:42.192] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/opc/servers/VireynMCOBT/libraries/net/minecraftforge/fmlcore/1.18.2-40.2.1/fmlcore-1.18.2-40.2.1.jar is missing mods.toml file
[30Mar2023 00:14:42.194] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/opc/servers/VireynMCOBT/libraries/net/minecraftforge/javafmllanguage/1.18.2-40.2.1/javafmllanguage-1.18.2-40.2.1.jar is missing mods.toml file
[30Mar2023 00:14:42.195] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/opc/servers/VireynMCOBT/libraries/net/minecraftforge/lowcodelanguage/1.18.2-40.2.1/lowcodelanguage-1.18.2-40.2.1.jar is missing mods.toml file
[30Mar2023 00:14:42.197] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/opc/servers/VireynMCOBT/libraries/net/minecraftforge/mclanguage/1.18.2-40.2.1/mclanguage-1.18.2-40.2.1.jar is missing mods.toml file
[30Mar2023 00:14:42.248] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[30Mar2023 00:14:43.433] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[30Mar2023 00:14:43.434] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[30Mar2023 00:14:44.507] [main/INFO] [org.magmafoundation.magma.protect.InjectProtect/]: Booting up InjectProtect
[30Mar2023 00:14:48.135] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 40.2.1, for MC 1.18.2 with MCP 20220404.173914
[30Mar2023 00:14:48.137] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v40.2.1 Initialized
[30Mar2023 00:14:48.815] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[30Mar2023 00:14:49.219] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: AHEAD Current: 40.2.1 Target: null
[30Mar2023 00:14:49.634] [main/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[30Mar2023 00:14:49.672] [main/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/home/opc/servers/VireynMCOBT/libraries/net/minecraft/server/1.18.2-20220404.173914/server-1.18.2-20220404.173914-srg.jar%2352!/assets/.mcassetsroot' uses unexpected schema
[30Mar2023 00:14:49.672] [main/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/home/opc/servers/VireynMCOBT/libraries/net/minecraft/server/1.18.2-20220404.173914/server-1.18.2-20220404.173914-srg.jar%2352!/data/.mcassetsroot' uses unexpected schema
[30Mar2023 00:14:49.694] [main/INFO] [net.minecraft.server.MinecraftServer/]: Found new data pack file/bukkit, loading it automatically
[30Mar2023 00:14:49.694] [main/INFO] [net.minecraft.server.MinecraftServer/]: Found new data pack iceandfire:data, loading it automatically
[30Mar2023 00:14:49.699] [main/INFO] [net.minecraft.server.MinecraftServer/]: Found new data pack file/bukkit, loading it automatically
[30Mar2023 00:14:49.700] [main/INFO] [net.minecraft.server.MinecraftServer/]: Found new data pack iceandfire:data, loading it automatically
[30Mar2023 00:14:51.813] [Worker-Main-5/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 8 recipes
[30Mar2023 00:14:53.023] [main/INFO] [org.magmafoundation.magma.patcher.PatcherManager/]: WorldEdit [Patches WorldEdit] loaded
[30Mar2023 00:14:53.023] [main/INFO] [org.magmafoundation.magma.patcher.PatcherManager/]: 1 patches loaded!
[30Mar2023 00:14:53.061] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting minecraft server version 1.18.2
[30Mar2023 00:14:53.062] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Loading properties
[30Mar2023 00:14:53.138] [Server thread/INFO] [Minecraft/]: This server is running Magma version git-Magma-1.18.2-129359fa (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
[30Mar2023 00:14:53.619] [Server thread/INFO] [org.magmafoundation.magma.Magma/]: Injected 549 modded materials (125 blocks, 424 items)
[30Mar2023 00:14:53.649] [Server thread/INFO] [Minecraft/]: Debug logging is enabled
[30Mar2023 00:14:53.650] [Server thread/INFO] [/]: Server Ping Player Sample Count: 12
[30Mar2023 00:14:53.653] [Server thread/INFO] [Minecraft/]: Using 4 threads for Netty based IO
[30Mar2023 00:14:53.669] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Default game type: SURVIVAL
[30Mar2023 00:14:53.669] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Generating keypair
[30Mar2023 00:14:53.728] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting Minecraft server on *:25521
[30Mar2023 00:14:53.751] [Server thread/INFO] [net.minecraft.server.network.ServerConnectionListener/]: Using epoll channel type
[30Mar2023 00:14:54.859] [Server thread/INFO] [net.coreprotect.CoreProtect/]: [CoreProtect] Loading CoreProtect v21.3
[30Mar2023 00:14:54.860] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading LuckPerms v5.4.67
[30Mar2023 00:14:55.178] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Loading InventoryRollbackPlus v1.6.8
[30Mar2023 00:14:55.178] [Server thread/INFO] [me.neznamy.tab.platforms.bukkit.BukkitTAB/]: [TAB] Loading TAB v3.3.0
[30Mar2023 00:14:55.179] [Server thread/INFO] [dev.geco.gsit.GSitMain/]: [GSit] Loading GSit v1.4.1
[30Mar2023 00:14:55.509] [Server thread/INFO] [com.christian34.easyprefix.EasyPrefix/]: [EasyPrefix] Loading EasyPrefix v1.8.7
[30Mar2023 00:14:55.510] [Server thread/INFO] [com.ghostchu.coreprotecttnt.Main/]: [CoreProtectTNT] Loading CoreProtectTNT v2.3.1
[30Mar2023 00:14:55.510] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Loading ConsoleSpamFix v1.9.0
[30Mar2023 00:14:55.511] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loading BanManager v7.9.0
[30Mar2023 00:14:55.511] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Loading AuthMe v5.6.0-SNAPSHOT-b2598
[30Mar2023 00:14:55.512] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Loading JoinMessagePlus v3.3
[30Mar2023 00:14:55.514] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Enabling LuckPerms v5.4.67
[30Mar2023 00:14:56.267] [Server thread/INFO] [/]: [0;36;1m       [0;36;22m __    [m
[30Mar2023 00:14:56.268] [Server thread/INFO] [/]: [0;36;1m  |    [0;36;22m|__)   [0;32;22mLuckPerms[m [0;36;1mv5.4.67[m
[30Mar2023 00:14:56.268] [Server thread/INFO] [/]: [0;36;1m  |___ [0;36;22m|      [0;30;1mRunning on Bukkit - Magma[m
[30Mar2023 00:14:56.269] [Server thread/INFO] [/]: [m
[30Mar2023 00:14:56.279] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading configuration...
[30Mar2023 00:14:56.705] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading storage provider... [H2]
[30Mar2023 00:14:58.268] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Loading internal permission managers...
[30Mar2023 00:14:58.423] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Performing initial data load...
[30Mar2023 00:14:58.603] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Successfully enabled. (took 3088ms)
[30Mar2023 00:14:58.607] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Enabling ConsoleSpamFix v1.9.0
[30Mar2023 00:14:58.609] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Server version detected: 1.18.2
[30Mar2023 00:14:58.612] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Loading the config file...
[30Mar2023 00:14:58.614] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Config file loaded!
[30Mar2023 00:14:58.626] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] ConsoleSpamFix loaded successfully!
[30Mar2023 00:14:58.627] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[30Mar2023 00:14:58.627] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: The server will make no attempt to authenticate usernames. Beware.
[30Mar2023 00:14:58.627] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[30Mar2023 00:14:58.628] [Server thread/WARN] [net.minecraft.server.dedicated.DedicatedServer/]: To change this, set "online-mode" to "true" in the server.properties file.
[30Mar2023 00:14:58.643] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file ./world/serverconfig/forge-server.toml is not correct. Correcting
[30Mar2023 00:14:58.644] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server was corrected from null to its default, SimpleCommentedConfig:{}. 
[30Mar2023 00:14:58.645] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.removeErroringBlockEntities was corrected from null to its default, false. 
[30Mar2023 00:14:58.645] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.removeErroringEntities was corrected from null to its default, false. 
[30Mar2023 00:14:58.645] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.fullBoundingBoxLadders was corrected from null to its default, false. 
[30Mar2023 00:14:58.646] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.zombieBaseSummonChance was corrected from null to its default, 0.1. 
[30Mar2023 00:14:58.646] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.zombieBabyChance was corrected from null to its default, 0.05. 
[30Mar2023 00:14:58.646] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.treatEmptyTagsAsAir was corrected from null to its default, false. 
[30Mar2023 00:14:58.647] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.skipEmptyShapelessCheck was corrected from null to its default, true. 
[30Mar2023 00:14:58.647] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.fixAdvancementLoading was corrected from null to its default, true. 
[30Mar2023 00:14:58.647] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key server.permissionHandler was corrected from null to its default, forge:default_handler. 
[30Mar2023 00:14:59.569] [Server thread/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Loaded 8 recipes
[30Mar2023 00:15:00.074] [Server thread/INFO] [Minecraft/]: Server permissions file permissions.yml is empty, ignoring it
[30Mar2023 00:15:00.531] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Preparing level "world"
[30Mar2023 00:15:00.542] [Server thread/INFO] [Minecraft/]: -------- World Settings For [world] --------
[30Mar2023 00:15:00.543] [Server thread/INFO] [Minecraft/]: Experience Merge Radius: 3.0
[30Mar2023 00:15:00.543] [Server thread/INFO] [Minecraft/]: Mob Spawn Range: 6
[30Mar2023 00:15:00.544] [Server thread/INFO] [Minecraft/]: Cactus Growth Modifier: 100%
[30Mar2023 00:15:00.544] [Server thread/INFO] [Minecraft/]: Cane Growth Modifier: 100%
[30Mar2023 00:15:00.544] [Server thread/INFO] [Minecraft/]: Melon Growth Modifier: 100%
[30Mar2023 00:15:00.545] [Server thread/INFO] [Minecraft/]: Mushroom Growth Modifier: 100%
[30Mar2023 00:15:00.545] [Server thread/INFO] [Minecraft/]: Pumpkin Growth Modifier: 100%
[30Mar2023 00:15:00.545] [Server thread/INFO] [Minecraft/]: Sapling Growth Modifier: 100%
[30Mar2023 00:15:00.545] [Server thread/INFO] [Minecraft/]: Beetroot Growth Modifier: 100%
[30Mar2023 00:15:00.545] [Server thread/INFO] [Minecraft/]: Carrot Growth Modifier: 100%
[30Mar2023 00:15:00.546] [Server thread/INFO] [Minecraft/]: Potato Growth Modifier: 100%
[30Mar2023 00:15:00.546] [Server thread/INFO] [Minecraft/]: Wheat Growth Modifier: 100%
[30Mar2023 00:15:00.546] [Server thread/INFO] [Minecraft/]: NetherWart Growth Modifier: 100%
[30Mar2023 00:15:00.546] [Server thread/INFO] [Minecraft/]: Vine Growth Modifier: 100%
[30Mar2023 00:15:00.546] [Server thread/INFO] [Minecraft/]: Cocoa Growth Modifier: 100%
[30Mar2023 00:15:00.547] [Server thread/INFO] [Minecraft/]: Bamboo Growth Modifier: 100%
[30Mar2023 00:15:00.547] [Server thread/INFO] [Minecraft/]: SweetBerry Growth Modifier: 100%
[30Mar2023 00:15:00.547] [Server thread/INFO] [Minecraft/]: Kelp Growth Modifier: 100%
[30Mar2023 00:15:00.549] [Server thread/INFO] [Minecraft/]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[30Mar2023 00:15:00.551] [Server thread/INFO] [Minecraft/]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[30Mar2023 00:15:00.552] [Server thread/INFO] [Minecraft/]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[30Mar2023 00:15:00.556] [Server thread/INFO] [Minecraft/]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[30Mar2023 00:15:00.557] [Server thread/INFO] [Minecraft/]: Max TNT Explosions: 100
[30Mar2023 00:15:00.557] [Server thread/INFO] [Minecraft/]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[30Mar2023 00:15:00.558] [Server thread/INFO] [Minecraft/]: View Distance: 32
[30Mar2023 00:15:00.558] [Server thread/INFO] [Minecraft/]: Simulation Distance: 10
[30Mar2023 00:15:00.558] [Server thread/INFO] [Minecraft/]: Item Despawn Rate: 6000
[30Mar2023 00:15:00.558] [Server thread/INFO] [Minecraft/]: Item Merge Radius: 2.5
[30Mar2023 00:15:00.559] [Server thread/INFO] [Minecraft/]: Allow Zombie Pigmen to spawn from portal blocks: true
[30Mar2023 00:15:00.559] [Server thread/INFO] [Minecraft/]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[30Mar2023 00:15:00.559] [Server thread/INFO] [Minecraft/]: Zombie Aggressive Towards Villager: true
[30Mar2023 00:15:00.560] [Server thread/INFO] [Minecraft/]: Nerfing mobs spawned from spawners: false
[30Mar2023 00:15:08.197] [Server thread/INFO] [net.coreprotect.CoreProtect/]: [CoreProtect] Enabling CoreProtect v21.3
[30Mar2023 00:15:08.798] [Server thread/INFO] [/]: [0;37;1m[0;37;1m[m[CoreProtect] CoreProtect has been successfully enabled![0;37;1m[0;37;1m [m
[30Mar2023 00:15:08.798] [Server thread/INFO] [Minecraft/]: [CoreProtect] Using SQLite for data storage.
[30Mar2023 00:15:08.799] [Server thread/INFO] [Minecraft/]: --------------------
[30Mar2023 00:15:08.799] [Server thread/INFO] [Minecraft/]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[30Mar2023 00:15:08.799] [Server thread/INFO] [Minecraft/]: [CoreProtect] Discord: www.coreprotect.net/discord/
[30Mar2023 00:15:08.799] [Server thread/INFO] [Minecraft/]: --------------------
[30Mar2023 00:15:08.825] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Enabling InventoryRollbackPlus v1.6.8
[30Mar2023 00:15:08.866] [Server thread/INFO] [/]: [0;37;1m[[0;36;1mInventoryRollbackPlus[0;37;1m][m Inventory backup data is set to save to: YAML[m
[30Mar2023 00:15:08.881] [Server thread/INFO] [/]: [0;37;1m[[0;36;1mInventoryRollbackPlus[0;37;1m][m bStats are enabled[m
[30Mar2023 00:15:08.944] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] ====================================================
[30Mar2023 00:15:08.944] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  InventoryRollbackPlus works better if you use Paper 
[30Mar2023 00:15:08.944] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  as your server software. 
[30Mar2023 00:15:08.945] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]   
[30Mar2023 00:15:08.945] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  Paper offers significant performance improvements,
[30Mar2023 00:15:08.945] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  bug fixes, security enhancements and optional
[30Mar2023 00:15:08.945] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  features for server owners to enhance their server.
[30Mar2023 00:15:08.946] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]   
[30Mar2023 00:15:08.946] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  Paper includes Timings v2, which is significantly
[30Mar2023 00:15:08.946] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  better at diagnosing lag problems over v1.
[30Mar2023 00:15:08.947] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]   
[30Mar2023 00:15:08.947] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  All of your plugins should still work, and the
[30Mar2023 00:15:08.947] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  Paper community will gladly help you fix any issues.
[30Mar2023 00:15:08.948] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]   
[30Mar2023 00:15:08.948] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus]  Join the Paper Community @ https://papermc.io
[30Mar2023 00:15:08.948] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] ====================================================
[30Mar2023 00:15:08.949] [Server thread/INFO] [me.neznamy.tab.platforms.bukkit.BukkitTAB/]: [TAB] Enabling TAB v3.3.0
[30Mar2023 00:15:08.955] [Server thread/INFO] [/]: [TAB] Server version: 1.18.2 (v1_18_R2)[m
[30Mar2023 00:15:09.101] [Server thread/INFO] [/]: [TAB] Loaded NMS hook in 145ms[m
[30Mar2023 00:15:09.565] [Server thread/INFO] [/]: [TAB] [0;32;1mEnabled in 232ms[m
[30Mar2023 00:15:09.592] [Server thread/INFO] [dev.geco.gsit.GSitMain/]: [GSit] Enabling GSit v1.4.1
[30Mar2023 00:15:09.696] [Server thread/INFO] [/]: [0;37;22m[[0;33;22mGSit[0;37;22m][0;32;1m The plugin was successfully enabled.[m
[30Mar2023 00:15:09.732] [Server thread/INFO] [com.christian34.easyprefix.EasyPrefix/]: [EasyPrefix] Enabling EasyPrefix v1.8.7
[30Mar2023 00:15:10.402] [Server thread/INFO] [com.christian34.easyprefix.EasyPrefix/]: [EasyPrefix] Plugin has been enabled! Version: 1.8.7
[30Mar2023 00:15:10.403] [Server thread/INFO] [com.christian34.easyprefix.EasyPrefix/]: [EasyPrefix] If you like the plugin or you have suggestions, please write a review on spigotmc.org!
[30Mar2023 00:15:10.403] [Server thread/INFO] [com.christian34.easyprefix.EasyPrefix/]: [EasyPrefix] This software uses Sentry for anonymous user statistics. License: https://github.com/getsentry/sentry/blob/master/LICENSE
[30Mar2023 00:15:10.404] [Server thread/INFO] [com.ghostchu.coreprotecttnt.Main/]: [CoreProtectTNT] Enabling CoreProtectTNT v2.3.1
[30Mar2023 00:15:10.409] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Enabling BanManager v7.9.0
[30Mar2023 00:15:11.294] [Server thread/WARN] [/]: [Server thread] INFO me.confuser.banmanager.common.hikari.HikariDataSource - bm-local - Starting...
[30Mar2023 00:15:13.096] [Server thread/WARN] [/]: [Server thread] INFO me.confuser.banmanager.common.hikari.HikariDataSource - bm-local - Start completed.
[30Mar2023 00:15:14.194] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loaded 0 bans into memory
[30Mar2023 00:15:14.211] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loaded 0 mutes into memory
[30Mar2023 00:15:14.465] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loaded 0 ip bans into memory
[30Mar2023 00:15:14.480] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loaded 0 ip mutes into memory
[30Mar2023 00:15:14.517] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loaded 0 ip range bans into memory
[30Mar2023 00:15:14.550] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Loaded 0 name bans into memory
[30Mar2023 00:15:14.888] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2598
[30Mar2023 00:15:15.354] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] SQLite Setup finished
[30Mar2023 00:15:15.553] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Hooked into LuckPerms!
[30Mar2023 00:15:15.908] [Server thread/WARN] [fr.xephi.authme.AuthMe/]: [AuthMe] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[30Mar2023 00:15:16.372] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] AuthMe 5.6.0-SNAPSHOT build n.2598 successfully enabled!
[30Mar2023 00:15:16.374] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Enabling JoinMessagePlus v3.3
[30Mar2023 00:15:16.374] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] [#]==========< JoinMessagePlus >==========[#]
[30Mar2023 00:15:16.374] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Version: 3.3
[30Mar2023 00:15:16.374] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Web: https://dev.bukkit.org/bukkit-plugins/join-message-plus/
[30Mar2023 00:15:16.395] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Mode: BungeeCord + Standalone
[30Mar2023 00:15:16.396] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Plugin by AndyCraftz
[30Mar2023 00:15:16.404] [Server thread/INFO] [org.magmafoundation.magma.Magma/]: Reloaded 103 help topics
[30Mar2023 00:15:16.407] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[30Mar2023 00:15:16.969] [Worker-Main-14/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[30Mar2023 00:15:16.970] [Worker-Main-8/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[30Mar2023 00:15:17.426] [Worker-Main-5/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 0%
[30Mar2023 00:15:17.916] [Worker-Main-8/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 1%
[30Mar2023 00:15:18.408] [Worker-Main-15/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 2%
[30Mar2023 00:15:18.908] [Worker-Main-11/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 4%
[30Mar2023 00:15:19.408] [Worker-Main-12/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 6%
[30Mar2023 00:15:19.912] [Worker-Main-6/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 8%
[30Mar2023 00:15:20.413] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 10%
[30Mar2023 00:15:20.918] [Worker-Main-14/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 12%
[30Mar2023 00:15:21.415] [Worker-Main-1/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 15%
[30Mar2023 00:15:21.915] [Worker-Main-9/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 18%
[30Mar2023 00:15:22.417] [Worker-Main-7/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 21%
[30Mar2023 00:15:22.916] [Worker-Main-15/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 24%
[30Mar2023 00:15:23.417] [Worker-Main-10/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 26%
[30Mar2023 00:15:23.912] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 29%
[30Mar2023 00:15:24.413] [Worker-Main-8/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 33%
[30Mar2023 00:15:24.913] [Worker-Main-7/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 35%
[30Mar2023 00:15:25.416] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 38%
[30Mar2023 00:15:25.914] [Worker-Main-8/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 42%
[30Mar2023 00:15:26.419] [Worker-Main-13/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 45%
[30Mar2023 00:15:26.912] [Worker-Main-4/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 48%
[30Mar2023 00:15:27.414] [Worker-Main-12/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 52%
[30Mar2023 00:15:27.910] [Worker-Main-4/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 55%
[30Mar2023 00:15:28.414] [Worker-Main-11/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 58%
[30Mar2023 00:15:28.909] [Worker-Main-4/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 61%
[30Mar2023 00:15:29.409] [Worker-Main-13/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 66%
[30Mar2023 00:15:29.908] [Worker-Main-13/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 69%
[30Mar2023 00:15:30.409] [Worker-Main-9/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 71%
[30Mar2023 00:15:30.909] [Worker-Main-10/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 74%
[30Mar2023 00:15:31.413] [Worker-Main-10/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 78%
[30Mar2023 00:15:31.908] [Worker-Main-3/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 82%
[30Mar2023 00:15:32.414] [Worker-Main-15/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 84%
[30Mar2023 00:15:32.908] [Worker-Main-9/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 87%
[30Mar2023 00:15:33.410] [Worker-Main-10/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 90%
[30Mar2023 00:15:33.908] [Worker-Main-8/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 94%
[30Mar2023 00:15:34.429] [Worker-Main-10/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Preparing spawn area: 98%
[30Mar2023 00:15:34.576] [Server thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 18168 ms
[30Mar2023 00:15:34.576] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Done (35.937s)! For help, type "help"
[30Mar2023 00:15:34.584] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[30Mar2023 00:15:34.584] [Server thread/INFO] [org.magmafoundation.magma.Magma/]: Forwarding forge permission[magma:permission] to bukkit
[30Mar2023 00:15:34.585] [Server thread/INFO] [com.github.alexthe666.iceandfire.IceAndFire/]: {SPAWN_DRAGON_SKELETON_I_CF=true, HYDRA_CAVE_CF=true, SPAWN_SEA_SERPENT_CF=true, SPAWN_STYMPHALIAN_BIRD_CF=true, SPAWN_WANDERING_CYCLOPS_CF=true, PIXIE_VILLAGE_CF=false, SPAWN_DEATH_WORM_CF=true, FIRE_DRAGON_CAVE_CF=true, SIREN_ISLAND_CF=true, MYRMEX_HIVE_DESERT_CF=true, SPAWN_HIPPOCAMPUS_CF=true, FIRE_DRAGON_ROOST_CF=true, MYRMEX_HIVE_JUNGLE_CF=true, GORGON_TEMPLE_CF=false, COPPER_ORE_CF=true, SILVER_ORE_CF=true, LIGHTNING_DRAGON_CAVE_CF=true, SPAWN_DRAGON_SKELETON_F_CF=true, AMETHYST_ORE_CF=true, SPAWN_DRAGON_SKELETON_L_CF=true, LIGHTNING_LILY_CF=true, MAUSOLEUM_CF=false, ICE_DRAGON_CAVE_CF=true, GRAVEYARD_CF=false, SAPPHIRE_ORE_CF=true, LIGHTNING_DRAGON_ROOST_CF=true, CYCLOPS_CAVE_CF=true, FROST_LILY_CF=true, FIRE_LILY_CF=true, ICE_DRAGON_ROOST_CF=true}
[30Mar2023 00:15:34.585] [Server thread/INFO] [com.github.alexthe666.iceandfire.IceAndFire/]: {TROLL_S=true, HIPPOGRYPH=true, AMPHITHERE=true, COCKATRICE=true, TROLL_M=true, DREAD_LICH=true, TROLL_F=true}
[30Mar2023 00:15:34.593] [Server thread/INFO] [Minecraft/]: Timings Reset
[30Mar2023 00:15:34.615] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] The following commands are blocked whilst muted:
[30Mar2023 00:15:34.616] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] msg
[30Mar2023 00:15:34.616] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] The following commands are blocked whilst soft muted:
[30Mar2023 00:15:34.616] [Craft Scheduler Thread - 0/INFO] [/]: [0;37;1m[[0;36;1mInventoryRollbackPlus[0;37;1m][m Checking for updates...[m
[30Mar2023 00:15:34.616] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] msg
[30Mar2023 00:15:34.617] [Craft Scheduler Thread - 4/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[30Mar2023 00:15:34.618] [Craft Scheduler Thread - 4/WARN] [fr.xephi.authme.AuthMe/]: [AuthMe] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[30Mar2023 00:15:34.618] [Craft Scheduler Thread - 4/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[30Mar2023 00:15:34.650] [Craft Scheduler Thread - 1/INFO] [/]: [0;37;22m[[0;34;1mEasyPrefix[0;37;22m] [0;37;22mA new update is available at: [0;36;1mhttps://www.spigotmc.org/resources/44580/updates[m
[30Mar2023 00:15:34.656] [Craft Scheduler Thread - 4/WARN] [fr.xephi.authme.AuthMe/]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[30Mar2023 00:15:34.664] [Craft Scheduler Thread - 0/INFO] [/]: 
[30Mar2023 00:15:34.664] [Craft Scheduler Thread - 0/INFO] [/]: [0;36;1m===============================================================================
[30Mar2023 00:15:34.664] [Craft Scheduler Thread - 0/INFO] [/]: A minor update to InventoryRollbackPlus is available!
[30Mar2023 00:15:34.664] [Craft Scheduler Thread - 0/INFO] [/]: Download at https://www.spigotmc.org/resources/inventoryrollbackplus-1-8-1-16-x.85811/
[30Mar2023 00:15:34.665] [Craft Scheduler Thread - 0/INFO] [/]: (current: 1.6.8, latest: 1.6.9)
[30Mar2023 00:15:34.665] [Craft Scheduler Thread - 0/INFO] [/]: ===============================================================================
[30Mar2023 00:15:34.665] [Craft Scheduler Thread - 0/INFO] [/]: [m
[30Mar2023 00:17:35.615] [User Authenticator #1/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: UUID of player ImBayti4EkPF is b0488441-4d09-33e8-ad4b-3c2745a7fd74
[30Mar2023 00:17:36.949] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@1ca99d00
[30Mar2023 00:17:37.214] [Server thread/INFO] [/]: [0;30;1m[[0;32;1m+[0;30;1m] [0;37;1mImBayti4EkPF[m
[30Mar2023 00:17:37.320] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: ImBayti4EkPF[/46.229.60.15:64922] logged in with entity id 304 at (17.5, 67.0, -132.5)
[30Mar2023 00:17:37.424] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: ImBayti4EkPF has made the advancement [Ice and Fire]
[30Mar2023 00:17:56.743] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: ImBayti4EkPF lost connection: Disconnected
[30Mar2023 00:17:56.745] [Server thread/INFO] [/]: [0;30;1m[[0;31;22m-[0;30;1m] [0;37;1mImBayti4EkPF[m
[30Mar2023 00:17:56.761] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: ImBayti4EkPF left the game
[30Mar2023 00:18:02.542] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Stopping the server
[30Mar2023 00:18:02.585] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[30Mar2023 00:18:02.586] [Server thread/INFO] [eu.andycraftz.joinmessageplus.bukkit.JoinMessagePlus/]: [JoinMessagePlus] Disabling JoinMessagePlus v3.3
[30Mar2023 00:18:02.588] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Disabling AuthMe v5.6.0-SNAPSHOT-b2598
[30Mar2023 00:18:02.604] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Waiting for 0 tasks to finish
[30Mar2023 00:18:02.604] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] AuthMe 5.6.0-SNAPSHOT-b2598 disabled!
[30Mar2023 00:18:02.605] [Server thread/INFO] [me.confuser.banmanager.bukkit.BMBukkitPlugin/]: [BanManager] Disabling BanManager v7.9.0
[30Mar2023 00:18:02.607] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Disabling ConsoleSpamFix v1.9.0
[30Mar2023 00:18:02.608] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] Messages hidden since the server started: 0
[30Mar2023 00:18:02.608] [Server thread/INFO] [net.craftersland.consolefix.CSF/]: [ConsoleSpamFix] ConsoleSpamFix is disabled!
[30Mar2023 00:18:02.609] [Server thread/INFO] [com.ghostchu.coreprotecttnt.Main/]: [CoreProtectTNT] Disabling CoreProtectTNT v2.3.1
[30Mar2023 00:18:02.609] [Server thread/INFO] [com.christian34.easyprefix.EasyPrefix/]: [EasyPrefix] Disabling EasyPrefix v1.8.7
[30Mar2023 00:18:02.610] [Server thread/INFO] [dev.geco.gsit.GSitMain/]: [GSit] Disabling GSit v1.4.1
[30Mar2023 00:18:02.611] [Server thread/INFO] [/]: [0;37;22m[[0;33;22mGSit[0;37;22m][0;32;1m The plugin was successfully disabled.[m
[30Mar2023 00:18:02.612] [Server thread/INFO] [me.neznamy.tab.platforms.bukkit.BukkitTAB/]: [TAB] Disabling TAB v3.3.0
[30Mar2023 00:18:02.628] [Server thread/INFO] [/]: [TAB] [0;32;1mDisabled in 16ms[m
[30Mar2023 00:18:02.629] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Disabling InventoryRollbackPlus v1.6.8
[30Mar2023 00:18:02.629] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Setting shutdown state
[30Mar2023 00:18:02.630] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Saving player inventories...
[30Mar2023 00:18:02.630] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Done saving player inventories!
[30Mar2023 00:18:02.630] [Server thread/INFO] [com.nuclyon.technicallycoded.inventoryrollback.InventoryRollbackPlus/]: [InventoryRollbackPlus] Plugin is disabled!
[30Mar2023 00:18:02.631] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Disabling LuckPerms v5.4.67
[30Mar2023 00:18:02.631] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Starting shutdown process...
[30Mar2023 00:18:02.645] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Closing storage...
[30Mar2023 00:18:02.691] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin/]: [LuckPerms] Goodbye!
[30Mar2023 00:18:02.691] [Server thread/INFO] [net.coreprotect.CoreProtect/]: [CoreProtect] Disabling CoreProtect v21.3
[30Mar2023 00:18:02.692] [Server thread/INFO] [Minecraft/]: [CoreProtect] Finishing up data logging. Please wait...
[30Mar2023 00:18:02.775] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.776] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.776] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.776] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.776] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.776] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.777] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:02.777] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.777] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.777] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.777] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.778] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.778] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.778] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:02.778] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.778] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.779] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.779] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.779] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.779] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.779] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:02.779] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.780] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.780] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.780] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.780] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.780] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.781] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:02.781] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.781] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.781] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.781] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.781] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.782] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.782] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:02.782] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.782] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.782] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.782] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.783] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.783] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.783] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:02.783] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:02.783] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:02.784] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:02.784] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:02.784] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:02.784] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:02.784] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:03.291] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:03.293] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:03.293] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:03.293] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:03.293] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:03.293] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:03.294] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:03.294] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:03.294] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:03.294] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:03.294] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:03.294] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:03.295] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:03.295] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:03.295] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:03.295] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:03.295] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:03.296] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:03.296] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:03.296] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:03.296] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:03.296] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:03.296] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:03.297] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:03.297] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:03.297] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:03.297] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:03.297] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:03.297] [Thread-10/WARN] [/]: java.lang.IllegalStateException: CoreProtectPreLogEvent cannot be triggered asynchronously from primary server thread.
[30Mar2023 00:18:03.298] [Thread-10/WARN] [/]: 	at TRANSFORMER/forge@40.2.1/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574)
[30Mar2023 00:18:03.298] [Thread-10/WARN] [/]: 	at net.coreprotect.database.logger.BlockPlaceLogger.log(BlockPlaceLogger.java:82)
[30Mar2023 00:18:03.298] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.BlockPlaceProcess.process(BlockPlaceProcess.java:23)
[30Mar2023 00:18:03.298] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.process.Process.processConsumer(Process.java:140)
[30Mar2023 00:18:03.298] [Thread-10/WARN] [/]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:133)
[30Mar2023 00:18:03.298] [Thread-10/WARN] [/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[30Mar2023 00:18:03.393] [Server thread/INFO] [Minecraft/]: [CoreProtect] Success! Disabled CoreProtect v21.3
[30Mar2023 00:18:03.394] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[30Mar2023 00:18:03.494] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[30Mar2023 00:18:04.725] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[30Mar2023 00:18:09.728] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[30Mar2023 00:18:09.729] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[30Mar2023 00:18:09.744] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[30Mar2023 00:18:09.744] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[30Mar2023 00:18:09.744] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[30Mar2023 00:18:09.744] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
```

### Other Information

- [ ] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by TheBv** [comment]
Could you test if the same thing happens if you type `/reload` without ice and fire installed?
This should reload all datpacks and for some reason seems to break commands in YAWP as well...

**Comment by rostikmak** [comment]
I have same issue please can you fix them.

**Comment by TheBv** [comment]
@rostikmak Can you try out what I suggested in the above comment?

**Comment by rostikmak** [comment]
My actions:
I removed ice and fire
I started the server
**Plugin commands work**
I ran /reload
waited for the command to finish
**oh listen, it doesn't work, just like with ice and fire**
What can i do now 0-0
I need plugins and ice and fire this mod is awesome!

**Comment by TheBv** [comment]
I'll contact the maga devs, most likely it's an issue on their end.

**Comment by rostikmak** [comment]
oh thanks a lot and good luck!
i try install old version of magma (but magma auto update) i hope i wil find how to off auto update

**Comment by Bayti4EkPressF** [comment]
>

I have exactly the same...

**Comment by rostikmak** [comment]
hello, any news?

**Comment by TheBv** [comment]
https://git.magmafoundation.org/magmafoundation/Magma-1-18-x/-/issues/201
Nope not yet.
I looked if there's any way to reload bukkit commands from magma but I can't find a way.
I'm currently considering rewriting a thing in ice and fire that would also resolve the issue but I'm not sure how to approach this properly.

**Comment by TheBv** [comment]
Seems to have gotten fixed in the latest magma version. I'm releasing an update soon for ice and fire as well which should eliminate the need for ice and fire to reload datapacks in general as well.

**Comment by Ep1cNova** [comment]
> Seems to have gotten fixed in the latest magma version. I'm releasing an update soon for ice and fire as well which should eliminate the need for ice and fire to reload datapacks in general as well.

Ice and fire works for magma 1.18 but for the 1.12.2 versions it still crashes. No crash log to look at either. Just stops the server.
