### ISSUE TITLE
[Bug]: mod is almost uncompatible with Terralith

### ISSUE THREAD

**Issue by antoniwicz** [Alex-the-666/Ice_and_Fire#4934]
### What happened?

because of terralith biome`s logging ice and fire can`t capture biome properties and, actually, do not spawn any dragons or leviathans. BUT! It is really strange, `cause i also can`t find any dragons or dragon lairs in vanilla biomes with vanilla tags (hot, rainy and so on) with Terralith installed. And I`m really curios, `cause I`ve find hippogriffs and hyppocampuses. Please, can you solve this problem? Or add like addon. I love ice and fire really much, but terralith generation is so beautiful.

### Minecraft Version

1.18

### Ice and Fire version

iceandfire-2.1.12-1.18.2-beta2

### Citadel version

citadel-1.11.3-1.18.2

### Relevant log output

```shell
there is no crash logs, game was not crashed.
```

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by SiverDX** [comment]
problems with terralith should be fixed in the latest beta releases: https://github.com/AlexModGuy/Ice_and_Fire/tags for 1.18.2+

**Comment by MediateTaxBR** [comment]
Did the problem really got solved for you? Im experiencing the exact same problem still
