### ISSUE TITLE
[Bug]: Entities become invisible when changing config

### ISSUE THREAD

**Issue by RingingAsp98** [Alex-the-666/Ice_and_Fire#4971]
### What happened?

I'm trying to create a modpack, but when I modify the config to turn off the custom title and disable dragon griefing all entities become invisible. 
![2023-10-10_12 16 24](https://github.com/AlexModGuy/Ice_and_Fire/assets/49981344/341da033-7abf-4550-84b2-10b35d63d27e)

log: 
[latest.log](https://github.com/AlexModGuy/Ice_and_Fire/files/12855920/latest.log)

please I need help!

### Minecraft Version

1.16(CRASHES ONLY)

### Ice and Fire version

2.1.12

### Citadel version

1.8.1

### Other Information

- [X] I am using other mods besides Ice and Fire
- [X] I have attached a log file from the session that I have experienced this issue

**Comment by RingingAsp98** [comment]
the only way to fix it, is to reinstall all the modpack, and when I retry the problem show up again.
I tried to remove, citadel, iceandfire and iceandfire tweaks but when i load the world the problem shows up again...

**Comment by TheBv** [comment]
It's difficult to properly triage this issue. 
I'd take a look at the mods `ESSENTIAL Mod` and `wildfire` (not sure what the last one is might be `wildfire's female gender mod`?)
Both of these mods are mentioned in the log file at least.

**Comment by PakoJones88** [comment]
Hello. I'm also experiencing this issue in 1.18.2. After in-depth testing, I found out that this happens when ice and fire is installed along with alex's mobs. Hope this information helps.

**Comment by TheBv** [comment]
There must be more to it than just that though because when I'm running just ice and fire and alex mobs I'm not running into this issue.
Any other rendering/optimization mod you have running alongside?

**Comment by RingingAsp98** [comment]
I fixed it like months ago, but I just forgot to say it. it's the wildfire's female gender mod.

**Comment by TheBv** [comment]
Right it seems to mention that in the log as well actually. I'll close this for now if @PakoJones88 is still experiencing issues just make a comment and I'll reopen this.
