### ISSUE TITLE
Gorgons petrifying mobs even with blindfold

### ISSUE THREAD

**Issue by mser7** [Alex-the-666/Ice_and_Fire#706]
Have a zombie or villager wear a blindfold, the gorgon will still petrified them instead of meele them

**Comment by AlexModGuy** [comment]
fixed

**Comment by tyler489** [comment]
Can Confirm still happening when gorgons are in a group they still petrify eachother wearing blindfolds
